version: '3.8'

services:
  backend:
    build: ./trinity-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trinity_db
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    volumes:
      - ./trinity-backend:/app
      - backend_deps:/app/.venv
    networks:
      - trinity-network

  frontend:
    build: 
      context: ./trinity-frontend
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./trinity-frontend:/app
      - frontend_deps:/app/node_modules
      - frontend_next:/app/.next
    depends_on:
      - backend
    networks:
      - trinity-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trinity_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - trinity-network

volumes:
  postgres_data:
  backend_deps:
  frontend_deps:
  frontend_next:

networks:
  trinity-network:
    driver: bridge
